# Generated by Django 4.2.5 on 2023-12-28 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('square_footage', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('number_of_bedrooms', models.IntegerField()),
                ('number_of_bathrooms', models.IntegerField()),
                ('image', models.ImageField(upload_to='static/images/')),
                ('about', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('parking', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertytype')),
            ],
        ),
    ]
