# Generated by Django 4.2.5 on 2023-12-29 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='property_id',
            new_name='property',
        ),
    ]
